---
- name: VXVM-FS-creation-sybase-DB
  hosts: '{{ variable_host }}'
  order: sorted
  gather_facts: False
  remote_user: '{{ variable_user }}'
  become: '{{ become_true_false }}'
  become_method: '{{ variable_become_method }}'
  become_user: '{{ variable_become_user }}'

  vars:
    skip: 0
    path: /opt/VRTS/bin

  tasks:
    - name: Copy csv file to '{{ variable_host }}'
      copy:
        src: "{{ path_to_csv }}"
        dest: "/var/tmp/{{ variable_user }}_Rundeck{{ job_id }}-VxVM-setup.csv"
        mode: '0400'

    - name: Remove blank spaces from CSV to avoid errors
      shell: sed -i "s/ //g" /var/tmp/{{ variable_user }}_Rundeck{{ job_id }}-VxVM-setup.csv

    - name:
      shell: |
        vxdisk -o alldgs list > /var/tmp/{{ variable_user }}_Rundeck{{ job_id }}-vxvmBefore-`date +"%m_%d_%Y_%H_%M_%S"`.txt
        ls -l /var/tmp/*.txt
        id sybase
        if [ $? -eq 0 ]; then
           echo '====' > /dev/null;
        else
           echo FAILED: Install sybase first under /opt/sybase;
           exit 50;
        fi;
      register: contents_0
    - debug:
        msg:
          - " ---- Prechecks ------ "
          - "{{ contents_0.stdout }}"

    - name:
      shell: |
        echo --- given disks are free or not ---;
        for i in `grep id-disk /var/tmp/{{ variable_user }}_Rundeck{{ job_id }}-VxVM-setup.csv | awk -F"," '{print $1 ":" $2 ":" $3 ":" $4 ":" $5}'`;
        do
          {{path}}/vxdisk -o alldgs list | grep `echo $i | awk -F":" '{ print $3 }'` | grep 'auto:none' > /dev/null;
          if [ $? -eq 0 ]; then
            echo "===" > /dev/null;
          else
            echo FAILED: Double check list of disks;
            exit 100;
          fi;
        done;
        echo ----------------------------
        echo --- Take disks under VxVM control ---
        for i in `grep id-disk /var/tmp/{{ variable_user }}_Rundeck{{ job_id }}-VxVM-setup.csv | awk -F"," '{print $1 ":" $2 ":" $3 ":" $4 ":" $5}'`;
        do
          {{ path }}/vxdisksetup -i `echo $i|awk -F":" '{print $3}'`
          echo vxdisksetup -i `echo $i|awk -F":" '{print $3}'`
          echo ------;
          {{ path }}/vxdisk -o alldgs list | grep `echo $i|awk -F":" '{ print $3 }'` | grep 'auto:cdsdisk' > /dev/null;
          if [ $? -eq 0 ]; then
            echo '====' > /dev/null;
          else
            echo FAILED: Disk is not taken under VxVM control, plz investigate;
            exit 200;
          fi;
        done;
      register: contents_1
      when: not skip
    - debug:
        msg:
          - "=== PART-1 : Taking disks under VxVM control "
          - "{{ contents_1.stdout }}"
      when: not skip
